### ISSUE TITLE
[Backend] 배포

### ISSUE THREAD

**Issue by choigiseong** [choigiseong/todo-list#10]
- [x] AWS EC2를 이용해 배포한다. 수동으로 배포를 진행하며 자동배포는 금지, 배포도구 사용도 금지한다.
- [x] MySQL 사용, 데이터베이스와 웹 서버 모두 동일한 인스턴스를 사용한다.
- [x] 리눅스 서버에서 소스를 가져올 때는 git을 사용한다.
- [x] 배포 서버에는 항상 동작하고 있는 버전이 배포되어 있어야 한다. 또한 master 브랜치를 이용해서 서비스를 배포한다.

**Comment by kyupid** [comment]
배포를 완료했으므로 클로즈하겠습니다
