### ISSUE TITLE
[backend] 카드 객체에 리스트들 담기

### ISSUE THREAD

**Issue by kyupid** [choigiseong/todo-list#14]
![2021-04-07_18-50-39](https://user-images.githubusercontent.com/59721293/113823064-503c7d80-97d2-11eb-95a3-8f017308e33f.jpg)

**Comment by kyupid** [comment]
구현 과정

- 레포.findAll() 로 모든 카드를 Iterable에 담는다.
- 담은 카드들을 CardList라는 카드들을 관리하는 클래스에 아규먼트로 넣어준다
- CardList 생성자에서 divde()라는 내부메서드를 이용해 카드들을 `status`에 따라 분배한다
- `status`는 이넘으로 관리
- divde내에 for each 카드들을 sort()한다.
- sort()메서드는 card.getStatus()에 따른 변수에따라 status에 맞는 리스트에 담아준다.
- 최종적으로 만들어진 CardList를 JSON으로 내보낸다. 

---
맞닥뜨린 문제해결

- 디비에서 파인드올로 가져오는데 카드의 값을 가져올떄는 카드의생성자를 이용해서 카드의객체를 만든다

**Comment by choigiseong** [comment]
close
