### ISSUE TITLE
[iOS, backend] JK의 팀 요구사항

### ISSUE THREAD

**Issue by kyupid** [choigiseong/todo-list#23]
- 브랜치 전략이나, 팀원 구성, 어떤 규칙들을 정했는지 각자 저장소 readme 문서에 기록한다.
- 다 같이 기획서를 분석하고 분야별 기능 요구사항 목록을 구글 스프레드시트에 통합해서 정리한다. 해당 링크는 readme에 연결한다.

https://codesquad-members.slack.com/archives/C01T98XAWF7/p1617858233002500

**Comment by jung-yun** [comment]
- [ ] 팀 룰 정하기
- [ ] 팀 용어 정하기
- [ ] 시스템 구성도 작성
- [x] Git 사용(브랜치) 전략
- [x] api 설계협의

**Comment by kyupid** [comment]
마지막 데모 시작전 서로 아쉬웠던점과 좋았던점을 공유하면서 JK가 주요적으로 원하던 요구사항을 해결했다고 판단하므로 클로즈하겠습니다
