### ISSUE TITLE
[Backend] log 관리

### ISSUE THREAD

**Issue by choigiseong** [choigiseong/todo-list#8]
- add, delete , update 시 log가 남아야 한다.
- cardService에서 log도 같이 update한다.

**Comment by kyupid** [comment]
진행중....?
[Initial README.md](https://github.com/ChoiGiSung/todo-list/commit/45ef9f4d5ce03af9a8f6c54b94942139d5134aba) 참조

**Comment by kyupid** [comment]
완료
